## Question 1

Importing Libraries

In [ ]:
%matplotlib inline
import matplotlib.pyplot as mplb

import numpy as npy

import pandas as pf

Importing the dataset

In [ ]:
pd=pf.read_csv("imports-85.csv")
pd.head()

,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.60,...,130,mpfi,3.47,2.68,9.00,111,5000,21,27,13495
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250

Giving Names to the Columns

In [ ]:
pd.columns=['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration', 'num-of-doors',
                'body-style', 'drive-wheels', 'engine-location', 'wheel-base', 'length', 'width', 'height',
                'curb-weight', 'engine-type', 'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
                'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg', 'highway-mpg', 'price']
pd.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250

In [ ]:
pd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          204 non-null    int64
 1   normalized-losses  204 non-null    object
 2   make               204 non-null    object
 3   fuel-type          204 non-null    object
 4   aspiration         204 non-null    object
 5   num-of-doors       204 non-null    object
 6   body-style         204 non-null    object
 7   drive-wheels       204 non-null    object
 8   engine-location    204 non-null    object
 9   wheel-base         204 non-null    float64
 10  length             204 non-null    float64
 11  width              204 non-null    float64
 12  height             204 non-null    float64
 13  curb-weight        204 non-null    int64
 14  engine-type        204 non-null    object
 15  num-of-cylinders   204 non-null    object
 16  engine-size        204 non-null    int64
 17  fuel-system        204 non-null    object
 18  bore               204 non-null    object
 19  stroke             204 non-null    object
 20  compression-ratio  204 non-null    float64
 21  horsepower         204 non-null    object
 22  peak-rpm           204 non-null    object
 23  city-mpg           204 non-null    int64
 24  highway-mpg        204 non-null    int64
 25  price              204 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.6+ KB

Dropping Columns with Non-Numeric Values

In [ ]:
pd.drop(pd.columns[[2,3,4,5,6,7,8,14,15,17]],axis=1,inplace=True)
pd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          204 non-null    int64
 1   normalized-losses  204 non-null    object
 2   wheel-base         204 non-null    float64
 3   length             204 non-null    float64
 4   width              204 non-null    float64
 5   height             204 non-null    float64
 6   curb-weight        204 non-null    int64
 7   engine-size        204 non-null    int64
 8   bore               204 non-null    object
 9   stroke             204 non-null    object
 10  compression-ratio  204 non-null    float64
 11  horsepower         204 non-null    object
 12  peak-rpm           204 non-null    object
 13  city-mpg           204 non-null    int64
 14  highway-mpg        204 non-null    int64
 15  price              204 non-null    object
dtypes: float64(5), int64(5), object(6)
memory usage: 25.6+ KB

Replacing '?' with 'nan'

In [ ]:
pd.replace('?',npy.nan, inplace=True)
pd

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
200,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
201,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
202,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
203,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

Converting data to type Float

In [ ]:
pd[pd.columns[[1,8,9,11,12,15]]]=pd[pd.columns[[1,8,9,11,12,15]]].astype(float)

Deleting Rows with multiple missing Values

In [ ]:
pd.dropna(axis=0, thresh=2, inplace=True)
pd

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
200,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
201,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
202,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
203,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

Replacing NaN values with mean of the respective column

In [ ]:
pd = pd.fillna(pd.mean())
pd

C:\Users\manda\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
200,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
201,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
202,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
203,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

Normalizing Values(except 'price' column)


Formula for Normalization : ((val - min(val))/(max(val)-min(val)))

In [ ]:
norm_pd=(pd-pd.min())/(pd.max()-pd.min())
norm_pd['price']=pd['price']
norm_pd

,symboling,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,1.0,0.298429,0.058309,0.413433,0.316667,0.083333,0.411171,0.260377,0.664286,0.290476,0.12500,0.262500,0.346939,0.222222,0.289474,16500.0
1,0.6,0.298429,0.230321,0.449254,0.433333,0.383333,0.517843,0.343396,0.100000,0.666667,0.12500,0.441667,0.346939,0.166667,0.263158,16500.0
2,0.8,0.518325,0.384840,0.529851,0.491667,0.541667,0.329325,0.181132,0.464286,0.633333,0.18750,0.225000,0.551020,0.305556,0.368421,13950.0
3,0.8,0.518325,0.373178,0.529851,0.508333,0.541667,0.518231,0.283019,0.464286,0.633333,0.06250,0.279167,0.551020,0.138889,0.157895,17450.0
4,0.8,0.298429,0.384840,0.540299,0.500000,0.441667,0.395268,0.283019,0.464286,0.633333,0.09375,0.258333,0.551020,0.166667,0.236842,15250.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,0.2,0.157068,0.655977,0.711940,0.716667,0.641667,0.567882,0.301887,0.885714,0.514286,0.15625,0.275000,0.510204,0.277778,0.315789,16845.0
200,0.2,0.157068,0.655977,0.711940,0.708333,0.641667,0.605508,0.301887,0.885714,0.514286,0.10625,0.466667,0.469388,0.166667,0.236842,19045.0
201,0.2,0.157068,0.655977,0.711940,0.716667,0.641667,0.591156,0.422642,0.742857,0.380952,0.11250,0.358333,0.551020,0.138889,0.184211,21485.0
202,0.2,0.157068,0.655977,0.711940,0.716667,0.641667,0.670675,0.316981,0.335714,0.633333,1.00000,0.241667,0.265306,0.361111,0.289474,22470.0
203,0.2,0.157068,0.655977,0.711940,0.716667,0.641667,0.610551,0.301887,0.885714,0.514286,0.15625,0.275000,0.510204,0.166667,0.236842,22625.0

Randomizing the data

In [ ]:
npy.random.seed(1)
sh_index=npy.random.permutation(norm_pd.index)
random_norm_pd=norm_pd.reindex(sh_index)

Spliting dataset into training, test and cross-validation sets

In [ ]:
train_set=random_norm_pd.iloc[:int(len(random_norm_pd)*0.5)]
cval_set=random_norm_pd.iloc[int(len(random_norm_pd)*0.5):int(len(random_norm_pd)*0.75)]
test_set=random_norm_pd.iloc[int(len(random_norm_pd)*0.75):]

In [ ]:
train_set

,symboling,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
127,1.0,0.298429,0.084548,0.414925,0.391667,0.316667,0.508922,0.501887,0.857143,0.395238,0.15625,0.662500,0.714286,0.111111,0.236842,37028.0
203,0.2,0.157068,0.655977,0.711940,0.716667,0.641667,0.610551,0.301887,0.885714,0.514286,0.15625,0.275000,0.510204,0.166667,0.236842,22625.0
18,0.6,0.172775,0.230321,0.220896,0.275000,0.350000,0.149728,0.109434,0.350000,0.495238,0.16250,0.091667,0.510204,0.694444,0.710526,6295.0
175,0.2,0.000000,0.460641,0.514925,0.516667,0.591667,0.359193,0.230189,0.550000,0.700000,0.10625,0.183333,0.020408,0.388889,0.421053,10898.0
196,0.2,0.047120,0.516035,0.711940,0.575000,0.808333,0.602793,0.301887,0.885714,0.514286,0.15625,0.275000,0.510204,0.305556,0.315789,16515.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,0.4,0.502618,0.620991,0.680597,0.675000,0.741667,0.594259,0.222642,0.657143,0.533333,0.08750,0.204167,0.346939,0.166667,0.210526,11900.0
36,0.4,0.214660,0.288630,0.394030,0.408333,0.458333,0.290147,0.184906,0.435714,0.719048,0.12500,0.158333,0.673469,0.388889,0.447368,7895.0
165,0.6,0.539267,0.230321,0.411940,0.308333,0.400000,0.314973,0.139623,0.500000,0.480952,0.15000,0.266667,1.000000,0.361111,0.342105,9538.0
190,0.4,0.298429,0.402332,0.583582,0.550000,0.608333,0.455004,0.283019,0.464286,0.633333,0.09375,0.258333,0.551020,0.166667,0.210526,13295.0
185,0.8,0.151832,0.311953,0.456716,0.433333,0.658333,0.305275,0.181132,0.464286,0.633333,0.12500,0.154167,0.448980,0.388889,0.473684,8495.0

In [ ]:
cval_set

,symboling,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
110,0.4,0.502618,0.620991,0.680597,0.675000,0.741667,0.615593,0.222642,0.657143,0.057143,0.08750,0.195833,0.346939,0.166667,0.210526,15580.0
107,0.4,0.502618,0.620991,0.680597,0.675000,0.741667,0.662917,0.343396,0.828571,0.690476,0.87500,0.195833,0.000000,0.416667,0.447368,13200.0
201,0.2,0.157068,0.655977,0.711940,0.716667,0.641667,0.591156,0.422642,0.742857,0.380952,0.11250,0.358333,0.551020,0.138889,0.184211,21485.0
116,0.4,0.502618,0.623907,0.680597,0.666667,0.683333,0.636928,0.275472,0.764286,0.542857,0.00000,0.391667,0.591837,0.138889,0.210526,18150.0
177,1.0,0.691099,0.475219,0.632836,0.616667,0.350000,0.577192,0.415094,0.521429,0.609524,0.14375,0.470833,0.428571,0.194444,0.210526,16558.0
75,0.8,0.502618,0.206997,0.241791,0.341667,0.250000,0.166796,0.116981,0.307143,0.552381,0.15000,0.083333,0.551020,0.666667,0.657895,5389.0
21,0.6,0.277487,0.206997,0.241791,0.291667,0.250000,0.150504,0.109434,0.307143,0.552381,0.15000,0.083333,0.551020,0.500000,0.578947,6377.0
91,0.6,0.298429,0.230321,0.361194,0.291667,0.558333,0.174554,0.135849,0.435714,0.580952,0.15000,0.087500,0.428571,0.500000,0.552632,6849.0
186,0.8,0.151832,0.311953,0.456716,0.433333,0.658333,0.322343,0.135849,0.335714,0.633333,1.00000,0.083333,0.142857,0.666667,0.684211,9495.0
2,0.8,0.518325,0.384840,0.529851,0.491667,0.541667,0.329325,0.181132,0.464286,0.633333,0.18750,0.225000,0.551020,0.305556,0.368421,13950.0
70,0.2,0.298429,0.845481,0.917910,0.950000,0.725000,0.873545,0.652830,0.657143,0.490476,0.08125,0.445833,0.244898,0.083333,0.052632,34184.0
85,0.6,0.314136,0.282799,0.467164,0.425000,0.316667,0.355702,0.230189,0.578571,0.661905,0.09375,0.166667,0.346939,0.333333,0.421053,8189.0
154,0.4,0.136126,0.265306,0.426866,0.275000,0.941667,0.629170,0.116981,0.364286,0.457143,0.12500,0.058333,0.265306,0.388889,0.421053,8778.0
6,0.6,0.298429,0.559767,0.770149,0.925000,0.658333,0.568658,0.283019,0.464286,0.633333,0.09375,0.258333,0.551020,0.166667,0.236842,18920.0
119,0.6,0.465969,0.206997,0.241791,0.291667,0.233333,0.185803,0.109434,0.307143,0.552381,0.15000,0.083333,0.551020,0.500000,0.578947,6229.0
0,1.0,0.298429,0.058309,0.413433,0.316667,0.083333,0.411171,0.260377,0.664286,0.290476,0.12500,0.262500,0.346939,0.222222,0.289474,16500.0
159,0.4,0.136126,0.265306,0.376119,0.341667,0.433333,0.235066,0.139623,0.464286,0.457143,0.12500,0.091667,0.265306,0.694444,0.815789,7738.0
77,0.8,0.502618,0.206997,0.241791,0.341667,0.250000,0.200155,0.116981,0.307143,0.552381,0.15000,0.083333,0.551020,0.500000,0.578947,6669.0
113,0.4,0.298429,0.804665,0.862687,0.675000,0.908333,0.774631,0.343396,0.828571,0.690476,0.87500,0.195833,0.000000,0.333333,0.236842,17075.0
65,0.4,0.298429,0.533528,0.505970,0.483333,0.550000,0.470132,0.275472,0.635714,0.747619,0.93750,0.100000,0.020408,0.500000,0.605263,18344.0
55,1.0,0.445026,0.253644,0.416418,0.450000,0.150000,0.346005,0.033962,0.563607,0.565857,0.15000,0.220833,0.755102,0.111111,0.184211,11845.0
132,0.8,0.204188,0.364431,0.679104,0.516667,0.691667,0.468192,0.226415,0.714286,0.476190,0.14375,0.258333,0.448980,0.222222,0.315789,12170.0
88,0.6,0.329843,0.230321,0.361194,0.291667,0.558333,0.155547,0.135849,0.435714,0.580952,0.15000,0.087500,0.428571,0.500000,0.552632,5499.0
193,0.0,0.198953,0.516035,0.711940,0.575000,0.700000,0.552366,0.301887,0.885714,0.514286,0.15625,0.275000,0.510204,0.277778,0.315789,12940.0
46,0.4,0.418848,0.769679,0.873134,0.775000,0.416667,1.000000,0.743396,0.778571,1.000000,0.06875,0.533333,0.244898,0.055556,0.078947,32250.0
62,0.4,0.298429,0.355685,0.547761,0.516667,0.641667,0.370442,0.230189,0.607143,0.628571,0.98125,0.066667,0.204082,0.638889,0.684211,10795.0
74,0.6,0.298429,0.469388,0.556716,0.641667,0.583333,0.551590,0.298113,0.885714,0.500000,0.06250,0.529167,0.346939,0.166667,0.210526,16503.0
92,0.6,0.198953,0.230321,0.434328,0.291667,0.475000,0.207913,0.135849,0.435714,0.580952,0.15000,0.087500,0.428571,0.500000,0.552632,7349.0
147,0.4,0.104712,0.300292,0.485075,0.425000,0.591667,0.361521,0.177358,0.771429,0.271429,0.12500,0.141667,0.265306,0.277778,0.342105,8013.0
87,0.2,0.376963,0.282799,0.467164,0.425000,0.316667,0.354926,0.184906,0.450000,0.661905,0.03125,0.283333,0.551020,0.277778,0.368421,9279.0
187,0.8,0.151832,0.311953,0.456716,0.433333,0.658333,0.314973,0.181132,0.464286,0.633333,0.18750,0.216667,0.551020,0.361111,0.421053,9995.0
10,0.4,0.664921,0.425656,0.532836,0.375000,0.541667,0.351823,0.177358,0.685714,0.347619,0.11250,0.220833,0.673469,0.277778,0.342105,16925.0
32,0.6,0.188482,0.206997,0.132836,0.308333,0.400000,0.175330,0.116981,0.264286,0.638095,0.13750,0.116667,0.755102,0.472222,0.473684,6529.0
83,1.0,0.298429,0.271137,0.479104,0.500000,0.200000,0.557797,0.358491,0.750000,0.852381,0.00000,0.404167,0.346939,0.166667,0.210526,14489.0
160,0.4,0.136126,0.265306,0.376119,0.341667,0.416667,0.245927,0.139623,0.464286,0.457143,0.12500,0.091667,0.265306,0.416667,0.473684,8358.0
100,0.4,0.329843,0.402332,0.605970,0.516667,0.608333,0.623351,0.452830,0.635714,0.571429,0.12500,0.433333,0.428571,0.111111,0.157895,13499.0
125,1.0,0.298429,0.084548,0.414925,0.391667,0.316667,0.491854,0.501887,0.857143,0.395238,0.15625,0.662500,0.714286,0.111111,0.236842,32528.0
23,0.6,0.434555,0.206997,0.241791,0.291667,0.233333,0.185803,0.109434,0.307143,0.552381,0.15000,0.083333,0.551020,0.500000,0.578947,6229.0
126,1.0,0.298429,0.084548,0.414925,0.391667,0.316667,0.491854,0.501887,0.857143,0.395238,0.15625,0.662500,0.714286,0.111111,0.236842,34028.0
9,0.8,0.664921,0.425656,0.532836,0.375000,0.541667,0.351823,0.177358,0.685714,0.347619,0.11250,0.220833,0.673469,0.277778,0.342105,16430.0
174,0.2,0.000000,0.460641,0.514925,0.516667,0.508333,0.359193,0.230189,0.550000,0.700000,0.10625,0.183333,0.020408,0.388889,0.421053,9988.0
104,1.0,0.675393,0.137026,0.441791,0.633333,0.158333,0.640419,0.452830,0.635714,0.571429,0.05000,0.633333,0.428571,0.111111,0.184211,19699.0
155,0.4,0.136126,0.265306,0.376119,0.341667,0.433333,0.230023,0.139623,0.464286,0.457143,0.12500,0.091667,0.265306,0.472222,0.552632,6938.0
135,1.0,0.445026,0.364431,0.679104,0.516667,0.691667,0.512025,0.226415,0.714286,0.476190,0.12500,0.466667,0.551020,0.166667,0.263158,18150.0
111,0.4,0.502618,0.620991,0.680597,0.675000,0.741667,0.684251,0.343396,0.828571,0.690476,0.87500,0.195833,0.000000,0.416667,0.447368,16900.0
197,0.0,0.198953,0.516035,0.711940,0.575000,0.700000,0.603957,0.260377,0.771429,0.514286,0.03125,0.475000,0.387755,0.111111,0.157895,18420.0
64,0.4,0.277487,0.533528,0.505970,0.483333,0.550000,0.458495,0.298113,0.871429,0.519048,0.06250,0.300000,0.346939,0.166667,0.289474,18280.0
15,0.4,0.298429,0.492711,0.786567,0.633333,0.491667,0.733902,0.558491,0.771429,0.628571,0.06250,0.558333,0.510204,0.083333,0.157895,41315.0
41,0.6,0.219895,0.288630,0.417910,0.475000,0.266667,0.312258,0.184906,0.435714,0.719048,0.13125,0.216667,0.551020,0.333333,0.394737,10345.0
167,0.8,0.361257,0.344023,0.523881,0.441667,0.350000,0.406517,0.320755,0.771429,0.680952,0.14375,0.283333,0.265306,0.305556,0.368421,9639.0
109,0.4,0.298429,0.804665,0.862687,0.675000,0.908333,0.753297,0.343396,0.828571,0.690476,0.87500,0.195833,0.000000,0.333333,0.236842,13860.0

In [ ]:
test_set

,symboling,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
80,1.0,0.460733,0.282799,0.476119,0.425000,0.133333,0.325834,0.230189,0.578571,0.661905,0.093750,0.166667,0.346939,0.333333,0.421053,8499.00
52,0.6,0.251309,0.189504,0.383582,0.325000,0.525000,0.177269,0.113208,0.350000,0.514286,0.125000,0.083333,0.346939,0.500000,0.578947,6695.00
26,0.6,0.434555,0.206997,0.241791,0.291667,0.233333,0.272692,0.139623,0.350000,0.628571,0.037500,0.225000,0.551020,0.305556,0.368421,8558.00
76,0.8,0.502618,0.206997,0.241791,0.341667,0.250000,0.176881,0.116981,0.307143,0.552381,0.150000,0.083333,0.551020,0.500000,0.578947,6189.00
43,0.6,0.298429,0.230321,0.220896,0.275000,0.350000,0.149728,0.109434,0.350000,0.495238,0.162500,0.091667,0.510204,0.694444,0.710526,13205.69
24,0.6,0.434555,0.206997,0.241791,0.291667,0.233333,0.194337,0.109434,0.307143,0.552381,0.150000,0.083333,0.551020,0.500000,0.578947,6692.00
3,0.8,0.518325,0.373178,0.529851,0.508333,0.541667,0.518231,0.283019,0.464286,0.633333,0.062500,0.279167,0.551020,0.138889,0.157895,17450.00
173,0.2,0.000000,0.460641,0.514925,0.516667,0.591667,0.384794,0.184906,0.521429,0.609524,0.968750,0.104167,0.142857,0.472222,0.447368,10698.00
49,0.6,0.204188,0.189504,0.268657,0.325000,0.525000,0.155935,0.113208,0.350000,0.514286,0.125000,0.083333,0.346939,0.472222,0.394737,5195.00
149,0.6,0.115183,0.265306,0.262687,0.275000,0.558333,0.192785,0.116981,0.364286,0.457143,0.125000,0.058333,0.265306,0.611111,0.605263,5348.00
131,1.0,0.445026,0.364431,0.679104,0.516667,0.691667,0.453840,0.226415,0.714286,0.476190,0.144375,0.258333,0.448980,0.222222,0.315789,11850.00
194,0.2,0.047120,0.516035,0.711940,0.575000,0.808333,0.599690,0.301887,0.885714,0.514286,0.156250,0.275000,0.510204,0.277778,0.315789,13415.00
30,0.8,0.376963,0.000000,0.052239,0.300000,0.250000,0.128394,0.116981,0.264286,0.638095,0.137500,0.116667,0.755102,0.500000,0.578947,6855.00
121,0.6,0.465969,0.206997,0.391045,0.291667,0.250000,0.272692,0.139623,0.307143,0.552381,0.150000,0.083333,0.551020,0.500000,0.578947,7609.00
115,0.4,0.502618,0.620991,0.680597,0.675000,0.741667,0.684251,0.343396,0.828571,0.690476,0.875000,0.195833,0.000000,0.416667,0.447368,17950.00
179,0.2,0.130890,0.521866,0.697015,0.516667,0.525000,0.637316,0.415094,0.521429,0.609524,0.137500,0.450000,0.428571,0.194444,0.210526,15690.00
8,0.4,0.298429,0.376093,0.553731,0.633333,0.350000,0.607060,0.264151,0.421429,0.633333,0.000000,0.466667,0.551020,0.083333,0.157895,13205.69
60,0.6,0.335079,0.355685,0.547761,0.516667,0.491667,0.347944,0.230189,0.607143,0.628571,0.100000,0.150000,0.265306,0.361111,0.421053,10595.00
128,0.6,0.298429,0.344023,0.516418,1.000000,0.225000,0.728472,0.535849,1.000000,0.495238,0.187500,1.000000,0.653061,0.111111,0.315789,13205.69
1,0.6,0.298429,0.230321,0.449254,0.433333,0.383333,0.517843,0.343396,0.100000,0.666667,0.125000,0.441667,0.346939,0.166667,0.263158,16500.00
57,1.0,0.445026,0.253644,0.416418,0.450000,0.150000,0.392552,0.071698,0.563607,0.565857,0.150000,0.362500,0.755102,0.083333,0.184211,15645.00
22,0.6,0.277487,0.206997,0.241791,0.291667,0.250000,0.248254,0.139623,0.350000,0.628571,0.037500,0.225000,0.551020,0.305556,0.368421,7957.00
61,0.4,0.261780,0.355685,0.547761,0.516667,0.641667,0.357642,0.230189,0.607143,0.628571,0.100000,0.150000,0.265306,0.361111,0.421053,10245.00
63,0.4,0.261780,0.355685,0.547761,0.516667,0.641667,0.363460,0.230189,0.607143,0.628571,0.100000,0.150000,0.265306,0.361111,0.421053,11245.00
7,0.6,0.486911,0.559767,0.770149,0.925000,0.675000,0.619860,0.264151,0.421429,0.633333,0.081250,0.383333,0.551020,0.111111,0.105263,23875.00
200,0.2,0.157068,0.655977,0.711940,0.708333,0.641667,0.605508,0.301887,0.885714,0.514286,0.106250,0.466667,0.469388,0.166667,0.236842,19045.00
141,0.4,0.193717,0.309038,0.461194,0.425000,0.391667,0.272304,0.177358,0.771429,0.271429,0.156250,0.141667,0.102041,0.416667,0.447368,7775.00
86,0.6,0.314136,0.282799,0.467164,0.425000,0.316667,0.354926,0.184906,0.450000,0.661905,0.031250,0.283333,0.551020,0.277778,0.368421,9279.00
96,0.6,0.198953,0.230321,0.434328,0.291667,0.475000,0.212956,0.135849,0.435714,0.580952,0.150000,0.087500,0.428571,0.500000,0.552632,7999.00
68,0.4,0.146597,0.586006,0.692537,0.833333,0.591667,0.778510,0.460377,0.742857,0.747619,0.906250,0.312500,0.081633,0.250000,0.236842,28176.00
50,0.6,0.204188,0.189504,0.268657,0.325000,0.525000,0.159814,0.113208,0.350000,0.514286,0.125000,0.083333,0.346939,0.500000,0.578947,6095.00
142,0.4,0.193717,0.309038,0.461194,0.425000,0.391667,0.330489,0.177358,0.771429,0.271429,0.125000,0.191667,0.428571,0.361111,0.421053,9960.00
157,0.4,0.136126,0.265306,0.376119,0.341667,0.433333,0.305275,0.184906,0.521429,0.609524,0.968750,0.033333,0.142857,0.583333,0.526316,7898.00
156,0.4,0.136126,0.265306,0.376119,0.341667,0.416667,0.240884,0.139623,0.464286,0.457143,0.125000,0.091667,0.265306,0.472222,0.552632,7198.00
139,0.8,0.094241,0.195335,0.241791,0.291667,0.658333,0.291699,0.177358,0.771429,0.271429,0.106250,0.104167,0.102041,0.361111,0.394737,7603.00
146,0.4,0.125654,0.303207,0.483582,0.425000,0.433333,0.375097,0.177358,0.771429,0.271429,0.125000,0.191667,0.428571,0.333333,0.394737,10198.00
101,0.4,0.225131,0.402332,0.649254,0.516667,0.691667,0.701319,0.452830,0.635714,0.571429,0.125000,0.433333,0.428571,0.111111,0.157895,14399.00
20,0.6,0.277487,0.206997,0.241791,0.291667,0.250000,0.150504,0.109434,0.307143,0.552381,0.150625,0.083333,0.551020,0.666667,0.657895,5572.00
178,1.0,0.691099,0.475219,0.632836,0.616667,0.350000,0.592708,0.415094,0.521429,0.609524,0.143750,0.470833,0.428571,0.166667,0.210526,15998.00
25,0.6,0.434555,0.206997,0.241791,0.291667,0.233333,0.194337,0.109434,0.307143,0.552381,0.150000,0.083333,0.551020,0.500000,0.578947,7609.00
134,0.8,0.204188,0.364431,0.679104,0.516667,0.691667,0.492630,0.226415,0.714286,0.476190,0.143750,0.258333,0.448980,0.222222,0.315789,15510.00
71,1.0,0.403141,0.291545,0.585075,0.850000,0.250000,0.852211,0.652830,0.657143,0.490476,0.081250,0.445833,0.244898,0.083333,0.052632,35056.00
129,0.4,0.298429,0.276968,0.602985,0.516667,0.616667,0.423196,0.267925,0.657143,0.871429,0.106250,0.234262,0.398363,0.277778,0.394737,9295.00
144,0.4,0.193717,0.303207,0.461194,0.425000,0.541667,0.396431,0.177358,0.771429,0.271429,0.043750,0.262500,0.265306,0.305556,0.342105,11259.00
192,0.4,0.298429,0.402332,0.626866,0.550000,0.608333,0.416990,0.181132,0.464286,0.633333,0.125000,0.166667,0.551020,0.333333,0.394737,12290.00
79,1.0,0.460733,0.282799,0.476119,0.425000,0.133333,0.342126,0.184906,0.450000,0.661905,0.031250,0.283333,0.551020,0.277778,0.368421,9959.00
133,1.0,0.445026,0.364431,0.679104,0.516667,0.691667,0.472847,0.226415,0.000000,0.000000,0.143750,0.258333,0.448980,0.222222,0.315789,15040.00
137,0.8,0.094241,0.206997,0.235821,0.258333,0.491667,0.217998,0.135849,0.771429,0.138095,0.125000,0.087500,0.306122,0.500000,0.526316,5118.00
72,0.4,0.298429,1.000000,1.000000,0.950000,0.741667,0.935609,0.932075,0.900000,0.609524,0.062500,0.566667,0.142857,0.027778,0.000000,40960.00
140,0.4,0.193717,0.309038,0.461194,0.425000,0.391667,0.254849,0.177358,0.771429,0.271429,0.156250,0.141667,0.265306,0.527778,0.552632,7126.00
37,0.4,0.214660,0.288630,0.394030,0.408333,0.458333,0.310706,0.184906,0.435714,0.719048,0.125000,0.158333,0.673469,0.388889,0.447368,9095.00

Calculating Euclidean Distance

In [ ]:
def euclidis(x,y):
    dis=0
    for i in range(len(x)-1):
        dis+=((x[i]-y[i])**2);
    return dis**(1/2)

KNN

In [ ]:
import operator
def getNeighbors(trainset,testinst,k):
    dist=[]
    
    for x in trainset.index:
        dis=euclidis(trainset.loc[x],testinst)
        dist.append((x,dis))
    dist.sort(key=operator.itemgetter(1))
    neighbors=[]
    for x in range(k):
        i=dist[x][0]
        ans=trainset.loc[i,"price"]
        neighbors.append(ans)
    return neighbors

Returning the average of KNN

In [ ]:
def knnfunct(trainset,testset,k):
    result=[]
    for x in testset.index:
        neighbors=getNeighbors(trainset,testset.loc[x],k)
        avg=npy.mean(neighbors)
        result.append(avg)
    return result

Root Mean Square Error(RMSE) Calculation

In [ ]:
def rmse(l1,l2):
    l=len(l1)
    sm=0
    for x in l1.index:
        sm+=((l1[x]-l2[x])**2)
    sm=sm/l
    return sm**(1/2)

Defining Function to get RMSE

In [ ]:
def knnmodel(train_set,test_set,k):
    ans={}
    l1=test_set["price"]
    l1=l1.reset_index(drop=True)
    for x in range(1,k+1):
        l2=knnfunct(train_set,test_set,x)
        ans.update({"k"+str(x):rmse(l1,l2)})
        
    return ans

Using Cross-Validation to figure out best value of k

In [ ]:
result=knnmodel(train_set,cval_set,5)
result

{'k1': 4532.3902601815125,
 'k2': 5379.563976151812,
 'k3': 5422.174151450923,
 'k4': 5277.084676426615,
 'k5': 4977.295856449481,
 'k6': 5236.607820995254,
 'k7': 5222.490295941648,
 'k8': 5220.565749320479,
 'k9': 5151.140824790105,
 'k10': 5333.212871273171,
 'k11': 5394.84548446638,
 'k12': 5461.460118499326,
 'k13': 5528.041243718225,
 'k14': 5582.57481036299,
 'k15': 5671.475524364262,
 'k16': 5718.051548605427,
 'k17': 5564.86424965088,
 'k18': 5634.699298278214,
 'k19': 5652.497277064558,
 'k20': 5642.98957395937,
 'k21': 5736.203601464098,
 'k22': 5788.373190568616,
 'k23': 5823.15133453076,
 'k24': 5905.456116187159,
 'k25': 5868.542474202477,
 'k26': 5930.239599577926,
 'k27': 5982.481918616775,
 'k28': 6047.614263326285,
 'k29': 6125.490110831265,
 'k30': 6202.703394992054,
 'k31': 6218.519536049059,
 'k32': 6270.789739222028,
 'k33': 6355.29344933161,
 'k34': 6387.204346460829,
 'k35': 6436.97065950462,
 'k36': 6487.109132305997,
 'k37': 6538.416182266218,
 'k38': 6536.892386910733,
 'k39': 6582.392382801274,
 'k40': 6636.659946146707,
 'k41': 6691.736044695863,
 'k42': 6740.706172168432,
 'k43': 6794.695418400752,
 'k44': 6796.832178977506,
 'k45': 6814.847254456173,
 'k46': 6815.7126723310585,
 'k47': 6846.809684093623,
 'k48': 6869.775349756248,
 'k49': 6900.1743726995755,
 'k50': 6918.816199670076,
 'k51': 6962.557631607201,
 'k52': 6981.284407435301,
 'k53': 7010.856427453841,
 'k54': 7050.517612189892,
 'k55': 7030.5710338273375,
 'k56': 7036.925671083474,
 'k57': 7052.376617520075,
 'k58': 7078.4583459795185,
 'k59': 7125.510534149243,
 'k60': 7151.037161019882,
 'k61': 7179.067863623906,
 'k62': 7150.2786260711955,
 'k63': 7165.070815181091,
 'k64': 7166.514425609693,
 'k65': 7176.538423492327,
 'k66': 7205.997868216273,
 'k67': 7159.322871454611,
 'k68': 7188.9985808577685,
 'k69': 7211.713164029342,
 'k70': 7253.906223410485,
 'k71': 7291.462140678782,
 'k72': 7323.4388188221565,
 'k73': 7342.531312047986,
 'k74': 7326.950524838189,
 'k75': 7365.4282183875675,
 'k76': 7385.199760852259,
 'k77': 7409.322654557379,
 'k78': 7450.703878563206,
 'k79': 7479.506095577705,
 'k80': 7509.479968453987,
 'k81': 7537.732507206907,
 'k82': 7561.409709464414,
 'k83': 7578.920551624362,
 'k84': 7556.910825502415,
 'k85': 7588.660895401869,
 'k86': 7614.361890041934,
 'k87': 7643.013933120804,
 'k88': 7673.322177752527,
 'k89': 7714.904747859464,
 'k90': 7751.330653646252,
 'k91': 7764.649551756432,
 'k92': 7797.8261745646,
 'k93': 7819.247639984203,
 'k94': 7838.16343479114,
 'k95': 7878.306715446262,
 'k96': 7912.026833141403,
 'k97': 7933.087777720991,
 'k98': 7976.284022029123,
 'k99': 8042.972968674483,
 'k100': 8101.340188777257}

Best Value for k is 1

So using KNN on test data with k=1

In [ ]:
res=knnmodel(train_set,test_set,1)
res

{'k1': 4794.405315774569}

## Question 2

Importing Libraries

In [ ]:
import numpy as npy
import pandas as pf

Importing Files containing datasets

In [ ]:
pd = pf.read_csv("adult.data.csv")
pd

                                                                                                                                                     |1x3 Cross validator
25  Private      226802  11th         7   Never-married       Machine-op-inspct  Own-child       Black               Male   0    0 40  United-States               <=50K.
38  Private      89814   HS-grad      9   Married-civ-spouse  Farming-fishing    Husband         White               Male   0    0 50  United-States               <=50K.
28  Local-gov    336951  Assoc-acdm   12  Married-civ-spouse  Protective-serv    Husband         White               Male   0    0 40  United-States                >50K.
44  Private      160323  Some-college 10  Married-civ-spouse  Machine-op-inspct  Husband         Black               Male   7688 0 40  United-States                >50K.
18  ?            103497  Some-college 10  Never-married       ?                  Own-child       White               Female 0    0 30  United-States               <=50K.
...                                                                                                                                                                   ...
39  Private      215419  Bachelors    13  Divorced            Prof-specialty     Not-in-family   White               Female 0    0 36  United-States               <=50K.
64  ?            321403  HS-grad      9   Widowed             ?                  Other-relative  Black               Male   0    0 40  United-States               <=50K.
38  Private      374983  Bachelors    13  Married-civ-spouse  Prof-specialty     Husband         White               Male   0    0 50  United-States               <=50K.
44  Private      83891   Bachelors    13  Divorced            Adm-clerical       Own-child       Asian-Pac-Islander  Male   5455 0 40  United-States               <=50K.
35  Self-emp-inc 182148  Bachelors    13  Married-civ-spouse  Exec-managerial    Husband         White               Male   0    0 60  United-States                >50K.

[16281 rows x 1 columns]

Giving Names to Columns

In [ ]:
pd.columns=['age','workclass','fnlwgt','education','education-num','marital-status','occupation','relationship','race','sex','capital-gain','capital-loss','hours-per-week','native-country','class']
pd.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K

Replacing Missing Values with Nan

In [ ]:
pd.replace(' ?',npy.nan,inplace=True)
pd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32560 entries, 0 to 32559
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32560 non-null  int64
 1   workclass       30724 non-null  object
 2   fnlwgt          32560 non-null  int64
 3   education       32560 non-null  object
 4   education-num   32560 non-null  int64
 5   marital-status  32560 non-null  object
 6   occupation      30717 non-null  object
 7   relationship    32560 non-null  object
 8   race            32560 non-null  object
 9   sex             32560 non-null  object
 10  capital-gain    32560 non-null  int64
 11  capital-loss    32560 non-null  int64
 12  hours-per-week  32560 non-null  int64
 13  native-country  31977 non-null  object
 14  class           32560 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

Changing data types of object columns to string

Dropping 3rd Column 'fnlwgt'

In [ ]:
pd[pd.columns[[1,3,5,6,7,8,9,13,14]]]=pd[pd.columns[[1,3,5,6,7,8,9,13,14]]].astype(str)

pd.drop(pd.columns[[2]],axis=1,inplace=True)
pd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32560 entries, 0 to 32559
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32560 non-null  int64
 1   workclass       32560 non-null  object
 2   education       32560 non-null  object
 3   education-num   32560 non-null  int64
 4   marital-status  32560 non-null  object
 5   occupation      32560 non-null  object
 6   relationship    32560 non-null  object
 7   race            32560 non-null  object
 8   sex             32560 non-null  object
 9   capital-gain    32560 non-null  int64
 10  capital-loss    32560 non-null  int64
 11  hours-per-week  32560 non-null  int64
 12  native-country  32560 non-null  object
 13  class           32560 non-null  object
dtypes: int64(5), object(9)
memory usage: 3.5+ MB

Replacing Nan Values with mode of respective columns

In [ ]:
pd=pd.fillna(pd.mode())
pd.head(50)

,age,workclass,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
0,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
5,49,Private,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
6,52,Self-emp-not-inc,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
7,31,Private,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
8,42,Private,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
9,37,Private,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
10,30,State-gov,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
11,23,Private,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
12,32,Private,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
13,40,Private,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,nan,>50K
14,34,Private,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
15,25,Self-emp-not-inc,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
16,32,Private,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
17,38,Private,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
18,43,Self-emp-not-inc,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K
19,40,Private,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
20,54,Private,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
21,35,Federal-gov,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,<=50K
22,43,Private,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K
23,59,Private,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
24,56,Local-gov,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
25,19,Private,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
26,54,nan,Some-college,10,Married-civ-spouse,nan,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
27,39,Private,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K
28,49,Private,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
29,23,Local-gov,Assoc-acdm,12,Never-married,Protective-serv,Not-in-family,White,Male,0,0,52,United-States,<=50K
30,20,Private,Some-college,10,Never-married,Sales,Own-child,Black,Male,0,0,44,United-States,<=50K
31,45,Private,Bachelors,13,Divorced,Exec-managerial,Own-child,White,Male,0,1408,40,United-States,<=50K
32,30,Federal-gov,Some-college,10,Married-civ-spouse,Adm-clerical,Own-child,White,Male,0,0,40,United-States,<=50K
33,22,State-gov,Some-college,10,Married-civ-spouse,Other-service,Husband,Black,Male,0,0,15,United-States,<=50K
34,48,Private,11th,7,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,Puerto-Rico,<=50K
35,21,Private,Some-college,10,Never-married,Machine-op-inspct,Own-child,White,Male,0,0,40,United-States,<=50K
36,19,Private,HS-grad,9,Married-AF-spouse,Adm-clerical,Wife,White,Female,0,0,25,United-States,<=50K
37,31,Private,Some-college,10,Married-civ-spouse,Sales,Husband,White,Male,0,0,38,nan,>50K
38,48,Self-emp-not-inc,Assoc-acdm,12,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
39,31,Private,9th,5,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,43,United-States,<=50K
40,53,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
41,24,Private,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,50,United-States,<=50K
42,49,Private,HS-grad,9,Separated,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
43,25,Private,HS-grad,9,Never-married,Handlers-cleaners,Not-in-family,White,Male,0,0,35,United-States,<=50K
44,57,Federal-gov,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Black,Male,0,0,40,United-States,>50K
45,53,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,38,United-States,<=50K
46,44,Private,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,40,United-States,<=50K
47,41,State-gov,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
48,29,Private,Assoc-voc,11,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,43,United-States,<=50K
49,25,Private,Some-college,10,Married-civ-spouse,Exec-managerial,Wife,Other,Female,0,0,40,United-States,<=50K

Defining a Node class denoting nodes in the tree

In [ ]:
class Node():
    def __init__(self, feat_in=None, thresh=None, left=None, right=None, i_g=None, val=None):
        #constructor 
        
        # for decision node
        self.feat_in = feat_in
        self.thresh = thresh
        self.left = left
        self.right = right
        self.i_g = i_g
        
        # for leaf node
        self.val = val

Creating a DT Classifer Class to do the classification(Most important methods are included here)

In [ ]:
class DTClassifier():
    def __init__(self, min_samples=2, depth=2):
        #constructor
        
        # initialize the root of the tree 
        self.root = None
        
        # stopping conditions
        self.min_samples = min_samples
        self.depth = depth
        
    def build_tree(self, ds, depth_n=0):
        #recursive function to build the tree
        
        X, Y = ds[:,:-1], ds[:,-1]
        nsamples, nfeatures = npy.shape(X)
        
        # split until stopping conditions are met
        if nsamples>=self.min_samples and depth_n<=self.depth:
            # find the best split
            best_split = self.get_split(ds, nsamples, nfeatures)
            # check if information gain is positive
            if best_split["i_g"]>0:
                # recur left
                lsubtree = self.build_tree(best_split["lds"], depth_n+1)
                # recur right
                rsubtree = self.build_tree(best_split["rds"], depth_n+1)
                # return decision node
                return Node(best_split["feat_in"], best_split["thresh"], 
                            lsubtree, rsubtree, best_split["i_g"])
        
        # compute leaf node
        leaf_val = self.calculate_leaf(Y)
        # return leaf node
        return Node(val=leaf_val)
    
    def get_split(self, ds, nsamples, nfeatures):
        #function to find the best split
        
        # dictionary to store the best split
        best_split = {}
        max_ig = -float("inf")
        
        # loop over all the features
        for feat_in in range(nfeatures):
            feat_val = ds[:, feat_in]
            possible_thresh = npy.unique(feat_val)
            # loop over all the feature values present in the data
            for thresh in possible_thresh:
                # get current split
                lds, rds = self.split(ds, feat_in, thresh)
                # check if childs are not null
                if len(lds)>0 and len(rds)>0:
                    y, ly, ry = ds[:, -1], lds[:, -1], rds[:, -1]
                    # compute information gain
                    curr_ig = self.i_g(y, ly, ry)
                    # update the best split if needed
                    if curr_ig>max_ig:
                        best_split["feat_in"] = feat_in
                        best_split["thresh"] = thresh
                        best_split["lds"] = lds
                        best_split["rds"] = rds
                        best_split["i_g"] = curr_ig
                        max_ig = curr_ig
                        
        # return best split
        return best_split
    
    def split(self, ds, feat_in, thresh):
        #function to split the data
        
        lds = npy.array([row for row in ds if row[feat_in]<=thresh])
        rds = npy.array([row for row in ds if row[feat_in]>thresh])
        return lds, rds
    
    def i_g(self, par, lchild, rchild):
        #function to compute information gain
        
        lweight = len(lchild) / len(par)
        rweight = len(rchild) / len(par)
        gain = self.entropy(par) - (lweight*self.entropy(lchild) + rweight*self.entropy(rchild))
        return gain
    
    def entropy(self, y):
        #function to compute entropy
        
        clabels = npy.unique(y)
        entropy = 0
        for c in clabels:
            pc = len(y[y == c]) / len(y)
            entropy += -pc * npy.log2(pc)
        return entropy
        
    def calculate_leaf(self, Y):
        #function to compute leaf node
        
        Y = list(Y)
        return max(Y, key=Y.count)
    
    def print_tree(self, tree=None, indent=" "):
        #function to print the tree
        
        if not tree:
            tree = self.root

        if tree.val is not None:
            print(tree.val)

        else:
            print("X_"+str(tree.feat_in), "<=", tree.thresh, "?", tree.i_g)
            print("%sleft:" % (indent), end="")
            self.print_tree(tree.left, indent + indent)
            print("%sright:" % (indent), end="")
            self.print_tree(tree.right, indent + indent)
    
    def fit(self, X, Y):
        #function to train the tree
        
        ds = npy.concatenate((X, Y), axis=1)
        self.root = self.build_tree(ds)
    
    def predict(self, X):
        #function to predict new dataset
        
        predictions = [self.predict_val(x, self.root) for x in X]
        return predictions
    
    def predict_val(self, x, tree):
        #function to predict a single data point 
        
        if tree.val!=None: return tree.val
        feature_val = x[tree.feat_in]
        if feature_val<=tree.thresh:
            return self.predict_val(x, tree.left)
        else:
            return self.predict_val(x, tree.right)

Getting the X and Y values so that X is input and Y stands for the prediction

In [ ]:
X = pd.iloc[:, :-1].values
Y = pd.iloc[:, -1].values.reshape(-1,1)

Creating an object of DTClassifier and running the method to get the DT for the dataset at hand

In [ ]:
classifier = DTClassifier(min_samples=3, depth=3)
classifier.fit(X,Y)
classifier.print_tree()

X_6 <=  Husband ? 0.11667662719588845
 left:X_3 <= 12 ? 0.0966532475217039
  left:X_9 <= 5013 ? 0.07584781818809061
    left:X_3 <= 8 ? 0.03012301021835062
        left: <=50K
        right: <=50K
    right:X_0 <= 61 ? 0.05884873943583553
        left: >50K
        right: >50K
  right:X_9 <= 5013 ? 0.07349499817298577
    left:X_10 <= 1740 ? 0.04642814208460422
        left: >50K
        right: >50K
    right:X_0 <= 62 ? 0.015354216260991996
        left: >50K
        right: >50K
 right:X_9 <= 6849 ? 0.07146940710064004
  left:X_6 <=  Unmarried ? 0.0600423703727343
    left:X_3 <= 12 ? 0.028390920717155987
        left: <=50K
        right: <=50K
    right:X_3 <= 10 ? 0.07280866366914429
        left: <=50K
        right: >50K
  right:X_3 <= 10 ? 0.051892745869312945
    left:X_0 <= 20 ? 0.07416241578618166
        left: <=50K
        right: >50K
    right: >50K

Predicting the values from the test dataset

In [ ]:
Y_pred = classifier.predict(X)
p=0
for i in range(len(Y_pred)):
    if Y_pred[i]==Y[i][0]:
        p+=1
acc=(p/len(Y_pred))*100
acc

84.44410319410319